### ISSUE TITLE
Issue with `BusinessValidationPipeline`

### ISSUE THREAD

**Issue by lonix1** [DavidRogersDev/ServerFramework#1]
I read your very interesting article [Validation without Exceptions using a MediatR Pipeline Behavior](https://medium.com/the-cloud-builders-guild/validation-without-exceptions-using-a-mediatr-pipeline-behavior-278f124836dc)... thanks!

The [accompanying code](https://github.com/DavidRogersDev/ServerFramework/blob/4382cf32c77306adb94643f38e9ce4d2ef4bde07/KesselRunFramework.AspNet/Messaging/Pipelines/BusinessValidationPipeline.cs#L47) is a little confusing.

If the `if (responseType.IsGenericType)` check fails, the request will simply be passed on to the next behavior (or ultimate handler) in the pipeline. In which case validation can fail silently.

But that code was written a while ago, how do you currently do this?

**Comment by DavidRogersDev** [comment]
Hi @lonix1 

Apologies for the belated response.

I think you raise a good point and I'll take a look at that. I can't remember my rationale and it may well be the case that the check is not required at all.

I'll come back once I've taken a good look at it.

Cheers

**Comment by lonix1** [comment]
No problem, we'll chat again in the future. I've excluded that bit and it seems to work, but I hope it doesn't blow up in the future because it handles some corner case I haven't yet imagined :)

**Comment by DavidRogersDev** [comment]
Hi @lonix1,

I finally got around to addressing this. I've now actually implemented the intention that only responses which are either `ValidateableResponses` or `ValidateableResponse<TModel>` can be handled by this Pipeline. Any response implementing `IValidateable` must return an object of either of those types.

That was the whole point of that particular Pipeline.

As an aside, I'm currently working on a branch which will remove MediatR and use an alternative CQRS implementation - hand-rolled by the author of SimpleInjector. (I never used the Publication feature of MediatR anyway - seemed like overkill to use it only for the Mediator and AOP stuff).

In addition, as per the current thinking of the author of SimpleInjector, the user can either use a mediator or directly inject the handler into the Controller (up to them, mileage may vary). The AOP stuff is still there and the `BusinessValidationPipeline` has been reborn as the `BusinessValidationDecorator`.

Closing this issue now. Happy to re-open if you find anything else with the updated code.

**Comment by lonix1** [comment]
I'm busy on another part of the system for now, but I'm keen to come back to this bit and refactor appropriately. I'll have a look and ping you if necessary.

Where do I find the new CQRS implementation? Everything Steven/DotnetJunkie makes is good, so I'm interested to have a look. I also think MediatR might be overkill. I'm currently toying with the idea of moving to the new net6 "minimal APIs", in which case MediatR might no longer be necessary as there could be some serious fat trimming if I go that route (pun intended).

Thanks for maintaining this very nice sample application.

**Comment by DavidRogersDev** [comment]
You can find the [new CQRS stuff here](https://github.com/DavidRogersDev/ServerFramework/tree/removemediatr) on the **_removemediatr_** branch.  
The existing controllers demonstrate how to directly inject the handlers into the controllers.    

There is a new [WorldZonesController.cs](https://github.com/DavidRogersDev/ServerFramework/blob/removemediatr/KesselRun.Web.Api/Controllers/V1.0/WorldZonesController.cs) which demonstrates DotNetJunkie's mediator. So, you can choose to use it where it looks like a controller would have too many handlers being injected in. It works basically the same as Mediatr, but predates it (I remember first grabbing it from a blog post he wrote in 2011). There's one for queries IQueryProcessor and one for commands ICommandProcessor. That is 2 separate pipelines (rather than Mediatr, which has only 1). But you could create even more e.g. if you wanted to support non-async pipelines.

I like the idea of alternative pipelines, because one pipeline may have decorators which are not relevant to another. With Mediatr, you need to use Interfaces to choose when some things get applied. So, I may have one Command-related pipeline for EF stuff and if it has legacy code as well, another Command-related pipeline for ADO.NET stuff (the transaction decorator would be different). The decorators (pipelines) [get registered here](https://github.com/DavidRogersDev/ServerFramework/blob/3b29739730edfac719953fd8a3ba5b810d303a36/KesselRun.Web.Api/Infrastructure/Ioc/DataAccessRegistry.cs#L43).

There's only 1 thing that I don't agree with DotNetJunkie about. He is a purist and believes that commands should not return anything. So his command abstraction returns void. I tend to work on smaller systems where the commands are not fire and forget and returning things is really handy e.g. a bool that an update succeeded. Perhaps he is right, but we find the constraints of DDD very limiting and don't use it. If you did want to go that way, the handler abstraction would look like this:

```
    public interface ICommandHandler<in TCommand>        
    {
        void Execute(TCommand command);
    }
```

Hope you find it interesting :)
